/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemLib */

#ifndef _Included_SystemLib
#define _Included_SystemLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemLib
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SystemLib_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     SystemLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SystemLib_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SystemLib
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SystemLib_reverse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
